### ISSUE TITLE
wrong definition of multidelay and pong

### ISSUE THREAD

**Issue by trebmuh** [ninodewit/SHIRO-Plugins#2]
Looking at https://github.com/ninodewit/SHIRO-Plugins/blob/master/plugins/multidelay/DistrhoPluginInfo.h and https://github.com/ninodewit/SHIRO-Plugins/blob/master/plugins/pong/DistrhoPluginInfo.h, it looks to have been copied, from the Modulay file, but forgotten to be adapted.

**Comment by ninodewit** [comment]
Multidelay, Pong and Pitchotto were just some tinkerings in Gen~ and should not be considered as stable plugins, but thanks for noticing. Did some cleanup.
