### ISSUE TITLE
Can these plug-ins be used on desktops as well?

### ISSUE THREAD

**Issue by unfa** [ninodewit/SHIRO-Plugins#5]
I'd like to be able to use these plug-ins with Ardour.

Is that possible?

**Comment by sub26nico** [comment]
+1. 
@unfa, you can load SHIRO-Plugins in Carla-Rack in Ardour, but automation ain't gonna be easy, 
but maybe using Carla's CC controls it is usable..

**Comment by ninodewit** [comment]
Sorry for the late reply. You might be able to get them in VST-format using https://github.com/Cycling74/gen-plugin-export

**Comment by unfa** [comment]
Thanks!
Would it possible to have them in LV2 format as well?

**Comment by ninodewit** [comment]
@falkTX can you chime in about this?

**Comment by falkTX** [comment]
@unfa did you try to build it yet?
you just run make and you get ladspa, lv2 and vst plugins right away (in the bin folder).

parameters are exposed just like any other plugin made with dpf, there should be no issues regarding automation. I dont know where this idea comes from...

**Comment by unfa** [comment]
I haven't honestly I have no idea where to start, and I've got some other stuff on my head right now, but if someone manages to get LV2 running in Ardour I'd love to give these a go too :)

**Comment by falkTX** [comment]
Here's a starting point ;)
```
sudo apt-get build-essential git
git clone --recursively https://github.com/ninodewit/SHIRO-Plugins.git
cd SHIRO-Plugins
make
```

**Comment by sub26nico** [comment]
I built it yesterday, but I had an error with
`git clone --recursively https://github.com/ninodewit/SHIRO-Plugins.git`
It works with 
`git clone --recursive  https://github.com/ninodewit/SHIRO-Plugins.git`

 Ardour can't see lv2, vst and ladspa. it's ok in Carla.
